'------------------------------------------------------------------------------
' <auto-generated>
'     Este código lo generó una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código. 
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class SiteMaster

    ''' <summary>
    ''' Control A1.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Control A2.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Control A3.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Control A4.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    ''' <summary>
    ''' Control MainContent.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
